# Generated by Django 4.2.2 on 2023-06-21 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Freelancers",
            fields=[
                (
                    "freelancer_id",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=50)),
                ("phone_number", models.IntegerField()),
                ("brand", models.CharField(max_length=50)),
                ("followers", models.CharField(max_length=50)),
                ("added_data", models.DateTimeField(auto_now=True)),
                (
                    "social_media",
                    models.CharField(
                        choices=[
                            ("Instagram", "Instagram"),
                            ("TIK TOK", "Tik-Tok"),
                            ("Twitter", "Twitter"),
                            ("Discord", "Discord"),
                            ("Twitch", "Twitch"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Brand",
            fields=[
                ("brand_id", models.AutoField(primary_key=True, serialize=False)),
                ("brand_name", models.CharField(max_length=50)),
                ("about", models.CharField(max_length=500)),
                (
                    "freelancers",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="api.freelancers",
                    ),
                ),
            ],
        ),
    ]
